services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - babyfoot-network

  backend:
    build: ./backend
    ports:
      - "5000:5000" # API
      - "5555:5555" # Prisma Studio
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - babyfoot-network

  db:
    image: postgres:15-alpine
    container_name: babyfoot-db
    restart: always
    environment:
      - POSTGRES_USER=jdoe
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=babyfoot_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - babyfoot-network

networks:
  babyfoot-network:
    driver: bridge

volumes:
  db-data: